TrainingArguments:
  target: 'SalesCount'
  ignore_features:
    - 'Id'
    - '1-Beratung?'
    - '1-Welches befristete AR haben Sie?'
    - '1-Test Sprache'
    - 'Zeitpunkt der Erstellung'
    - 'Sales'
    - 'Zeitpunkt der nderung'
    - 'Zeitpunkt der Erstellung - Year'
    - 'Zeitpunkt der nderung - Year'
  train_size: 0.7
  preprocess: true
  max_encoding_ohe: 1
  encoding_method: 'encoder'
  normalize: true
  normalize_method: 'minmax'
  feature_selection: true
  feature_selection_method: 'univariate'
  n_features_to_select: 0.25
  probability_threshold: 0.075
  cross_validation: true
  sort: 'F1'